### ISSUE TITLE
hpc-stack probably should install pnetcdf and enable it in PIO by default...

### ISSUE THREAD

**Issue by edwardhartnett** [NOAA-EMC/hpc-stack#102]
I'm still getting used to hpc-stack, but I see this in config/stack_noaa.yaml:
```
pio:
  build: YES
  version: 2.5.1
  enable_pnetcdf: NO
  enable_gptl: NO

```

Probably you want to build PIO with pnetcdf. It's the best performing parallel I/O layer, for classic format netCDF files. (It won't handle netCDF/HDF5 files.)
