### ISSUE TITLE
Install FMS library 

### ISSUE THREAD

**Issue by junwang-noaa** [NOAA-EMC/hpc-stack#199]
**Is your feature request related to a problem? Please describe.**
FMS is currently built in UFS. Since it does not change frequently, it would be more efficient to build it as a library and the UFS build system will link it at build time. 

**Describe the solution you'd like**
Now according to @aerorahul  FMS is in hpc-stack, please build the FMS library (both real4 and real8 libraries) at a test location on UFS supported platforms: dell, cray, hera, jet, orion, gaea, so that we can test it in the UFS.

**Comment by aerorahul** [comment]
@junwang-noaa 
This is the current build option for FMS from `stack_noaa.yaml`

```
fms:
  build: YES
  version: 2020.04.03
  repo: noaa-gfdl
  cmake_opts: "-DGFS_PHYS=ON -D64BIT=ON -DOPENMP=ON"
```

It will build the `2020.04.03` tag in both single and double precision libraries with `OpenMP`.
